splash = false
wallpaper {
  monitor = DP-1
  path = ~/.config/hypr/assets/wallpaper-dark.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = ~/.config/hypr/assets/wallpaper-dark.png
  fit_mode = cover
}